const CITY_OPTIONS = ["Tunis", "Sfax", "Sousse", "Bizerte", "Nabeul"];

function toIsoDaysAgo(daysAgo, hour = 10, minute = 15) {
  const value = new Date();
  value.setDate(value.getDate() - daysAgo);
  value.setHours(hour, minute, 0, 0);
  return value.toISOString();
}

function profileImage(index) {
  return `https://i.pravatar.cc/200?img=${index}`;
}

function idImage(seed) {
  return `https://picsum.photos/seed/repas-id-${seed}/1200/760`;
}

const DONORS = [
  {
    id: "d-001",
    name: "Amine Bougueddima",
    email: "amine.bougueddima@gmail.com",
    city: "Tunis",
    status: "actif",
    quizScore: 5,
    wrongAnswers: [],
    registeredAt: toIsoDaysAgo(45, 9, 10),
    phone: "+216 20 451 118",
    suspensionReason: "",
    photoUrl: profileImage(12),
    idPhotoUrl: idImage("amine"),
  },
  {
    id: "d-002",
    name: "Hadi Khemiri",
    email: "hadi.khemiri2022@gmail.com",
    city: "Sfax",
    status: "actif",
    quizScore: 5,
    wrongAnswers: [],
    registeredAt: toIsoDaysAgo(30, 8, 55),
    phone: "+216 54 093 411",
    suspensionReason: "",
    photoUrl: profileImage(33),
    idPhotoUrl: idImage("hadi"),
  },
  {
    id: "d-003",
    name: "Leila Bouzid",
    email: "leila.bouzid@repas.tn",
    city: "Nabeul",
    status: "en_attente",
    quizScore: 4,
    wrongAnswers: [1],
    registeredAt: toIsoDaysAgo(8, 11, 40),
    phone: "+216 21 600 339",
    suspensionReason: "",
    photoUrl: profileImage(42),
    idPhotoUrl: idImage("leila"),
  },
  {
    id: "d-004",
    name: "Khaled Gharbi",
    email: "khaled.gharbi@repas.tn",
    city: "Sousse",
    status: "suspendu",
    quizScore: 3,
    wrongAnswers: [0, 4],
    registeredAt: toIsoDaysAgo(52, 9, 5),
    phone: "+216 27 314 901",
    suspensionReason: "Signalements repetes sur des horaires non respectes.",
    photoUrl: profileImage(51),
    idPhotoUrl: idImage("khaled"),
  },
  {
    id: "d-005",
    name: "Sonia Trabelsi",
    email: "sonia.trabelsi@repas.tn",
    city: "Bizerte",
    status: "actif",
    quizScore: 5,
    wrongAnswers: [],
    registeredAt: toIsoDaysAgo(18, 10, 22),
    phone: "+216 93 218 820",
    suspensionReason: "",
    photoUrl: profileImage(58),
    idPhotoUrl: idImage("sonia"),
  },
  {
    id: "d-006",
    name: "Mariem Jouini",
    email: "mariem.jouini@repas.tn",
    city: "Tunis",
    status: "en_attente",
    quizScore: 4,
    wrongAnswers: [2],
    registeredAt: toIsoDaysAgo(6, 12, 10),
    phone: "+216 55 237 404",
    suspensionReason: "",
    photoUrl: profileImage(24),
    idPhotoUrl: idImage("mariem"),
  },
  {
    id: "d-007",
    name: "Yassine Cherif",
    email: "yassine.cherif@repas.tn",
    city: "Sfax",
    status: "actif",
    quizScore: 4,
    wrongAnswers: [3],
    registeredAt: toIsoDaysAgo(40, 8, 35),
    phone: "+216 22 997 512",
    suspensionReason: "",
    photoUrl: profileImage(17),
    idPhotoUrl: idImage("yassine"),
  },
  {
    id: "d-008",
    name: "Ines Ben Youssef",
    email: "ines.benyoussef@repas.tn",
    city: "Nabeul",
    status: "actif",
    quizScore: 5,
    wrongAnswers: [],
    registeredAt: toIsoDaysAgo(14, 14, 5),
    phone: "+216 29 518 800",
    suspensionReason: "",
    photoUrl: profileImage(65),
    idPhotoUrl: idImage("ines"),
  },
  {
    id: "d-009",
    name: "Firas Khelifi",
    email: "firas.khelifi@repas.tn",
    city: "Sousse",
    status: "suspendu",
    quizScore: 2,
    wrongAnswers: [0, 2, 4],
    registeredAt: toIsoDaysAgo(61, 9, 45),
    phone: "+216 24 430 119",
    suspensionReason: "Contenu inapproprie signale a plusieurs reprises.",
    photoUrl: profileImage(38),
    idPhotoUrl: idImage("firas"),
  },
  {
    id: "d-010",
    name: "Rim Saidi",
    email: "rim.saidi@repas.tn",
    city: "Tunis",
    status: "actif",
    quizScore: 4,
    wrongAnswers: [1],
    registeredAt: toIsoDaysAgo(20, 13, 15),
    phone: "+216 56 802 204",
    suspensionReason: "",
    photoUrl: profileImage(48),
    idPhotoUrl: idImage("rim"),
  },
  {
    id: "d-011",
    name: "Nader Ben Amor",
    email: "nader.benamor@repas.tn",
    city: "Bizerte",
    status: "actif",
    quizScore: 5,
    wrongAnswers: [],
    registeredAt: toIsoDaysAgo(26, 10, 48),
    phone: "+216 50 702 116",
    suspensionReason: "",
    photoUrl: profileImage(29),
    idPhotoUrl: idImage("nader"),
  },
  {
    id: "d-012",
    name: "Houda Mzoughi",
    email: "houda.mzoughi@repas.tn",
    city: "Sfax",
    status: "en_attente",
    quizScore: 4,
    wrongAnswers: [0],
    registeredAt: toIsoDaysAgo(4, 16, 30),
    phone: "+216 28 109 607",
    suspensionReason: "",
    photoUrl: profileImage(21),
    idPhotoUrl: idImage("houda"),
  },
  {
    id: "d-013",
    name: "Mehdi Chaieb",
    email: "mehdi.chaieb@repas.tn",
    city: "Nabeul",
    status: "actif",
    quizScore: 5,
    wrongAnswers: [],
    registeredAt: toIsoDaysAgo(33, 9, 21),
    phone: "+216 23 517 300",
    suspensionReason: "",
    photoUrl: profileImage(54),
    idPhotoUrl: idImage("mehdi"),
  },
  {
    id: "d-014",
    name: "Salma Karray",
    email: "salma.karray@repas.tn",
    city: "Sousse",
    status: "actif",
    quizScore: 5,
    wrongAnswers: [],
    registeredAt: toIsoDaysAgo(9, 12, 42),
    phone: "+216 98 220 443",
    suspensionReason: "",
    photoUrl: profileImage(66),
    idPhotoUrl: idImage("salma"),
  },
  {
    id: "d-015",
    name: "Walid Mansouri",
    email: "walid.mansouri@repas.tn",
    city: "Tunis",
    status: "actif",
    quizScore: 4,
    wrongAnswers: [2],
    registeredAt: toIsoDaysAgo(12, 10, 12),
    phone: "+216 25 703 514",
    suspensionReason: "",
    photoUrl: profileImage(39),
    idPhotoUrl: idImage("walid"),
  },
];

const RECEIVERS = [
  { id: "r-001", name: "Nour Ben Amor", email: "nour.benamor@repas.tn", city: "Tunis", registeredAt: toIsoDaysAgo(31, 10, 0), status: "actif", phone: "+216 53 100 230" },
  { id: "r-002", name: "Sami Kooli", email: "sami.kooli@repas.tn", city: "Sfax", registeredAt: toIsoDaysAgo(21, 9, 52), status: "actif", phone: "+216 20 333 441" },
  { id: "r-003", name: "Amel Jaziri", email: "amel.jaziri@repas.tn", city: "Sousse", registeredAt: toIsoDaysAgo(17, 15, 5), status: "actif", phone: "+216 55 990 112" },
  { id: "r-004", name: "Mounir Dakhli", email: "mounir.dakhli@repas.tn", city: "Bizerte", registeredAt: toIsoDaysAgo(11, 11, 40), status: "actif", phone: "+216 29 417 060" },
  { id: "r-005", name: "Aicha Bensalem", email: "aicha.bensalem@repas.tn", city: "Nabeul", registeredAt: toIsoDaysAgo(8, 13, 3), status: "actif", phone: "+216 21 511 189" },
  { id: "r-006", name: "Rami Smida", email: "rami.smida@repas.tn", city: "Tunis", registeredAt: toIsoDaysAgo(6, 14, 15), status: "actif", phone: "+216 28 140 010" },
  { id: "r-007", name: "Imen Guezguez", email: "imen.guezguez@repas.tn", city: "Sfax", registeredAt: toIsoDaysAgo(22, 8, 44), status: "actif", phone: "+216 57 990 222" },
  { id: "r-008", name: "Karim Frikha", email: "karim.frikha@repas.tn", city: "Sousse", registeredAt: toIsoDaysAgo(27, 10, 11), status: "actif", phone: "+216 24 101 900" },
  { id: "r-009", name: "Meriem Khlifi", email: "meriem.khlifi@repas.tn", city: "Bizerte", registeredAt: toIsoDaysAgo(15, 16, 27), status: "actif", phone: "+216 50 223 744" },
  { id: "r-010", name: "Tarek Ayedi", email: "tarek.ayedi@repas.tn", city: "Nabeul", registeredAt: toIsoDaysAgo(44, 9, 20), status: "suspendu", phone: "+216 25 401 387" },
];

const DONOR_BY_ID = Object.fromEntries(DONORS.map((item) => [item.id, item]));

const DONATIONS = [
  { id: "don-001", donorId: "d-001", description: "Couscous au poulet", quantity: "8 portions", city: "Tunis", publishedAt: toIsoDaysAgo(0, 9, 0), status: "disponible", receiverId: null, warningSent: false },
  { id: "don-002", donorId: "d-002", description: "Paniers de fruits", quantity: "4 paniers", city: "Sfax", publishedAt: toIsoDaysAgo(0, 11, 25), status: "reclame", receiverId: "r-001", warningSent: false },
  { id: "don-003", donorId: "d-005", description: "Sandwichs thon", quantity: "12 pieces", city: "Bizerte", publishedAt: toIsoDaysAgo(1, 10, 10), status: "reclame", receiverId: "r-003", warningSent: false },
  { id: "don-004", donorId: "d-007", description: "Plats de pates", quantity: "6 portions", city: "Sfax", publishedAt: toIsoDaysAgo(2, 13, 30), status: "disponible", receiverId: null, warningSent: false },
  { id: "don-005", donorId: "d-008", description: "Soupe chorba", quantity: "10 portions", city: "Nabeul", publishedAt: toIsoDaysAgo(3, 12, 10), status: "expire", receiverId: null, warningSent: false },
  { id: "don-006", donorId: "d-007", description: "Pain et viennoiseries", quantity: "25 pieces", city: "Sfax", publishedAt: toIsoDaysAgo(4, 8, 20), status: "reclame", receiverId: "r-004", warningSent: false },
  { id: "don-007", donorId: "d-010", description: "Laitages frais", quantity: "14 unites", city: "Tunis", publishedAt: toIsoDaysAgo(5, 10, 0), status: "disponible", receiverId: null, warningSent: false },
  { id: "don-008", donorId: "d-011", description: "Salades composees", quantity: "9 portions", city: "Bizerte", publishedAt: toIsoDaysAgo(6, 15, 40), status: "reclame", receiverId: "r-006", warningSent: false },
  { id: "don-009", donorId: "d-013", description: "Plats traditionnels", quantity: "7 portions", city: "Nabeul", publishedAt: toIsoDaysAgo(7, 9, 33), status: "disponible", receiverId: null, warningSent: false },
  { id: "don-010", donorId: "d-014", description: "Legumes cuits", quantity: "5 portions", city: "Sousse", publishedAt: toIsoDaysAgo(8, 12, 41), status: "expire", receiverId: null, warningSent: false },
  { id: "don-011", donorId: "d-007", description: "Riz et legumes", quantity: "8 portions", city: "Sfax", publishedAt: toIsoDaysAgo(10, 11, 12), status: "reclame", receiverId: "r-002", warningSent: false },
  { id: "don-012", donorId: "d-001", description: "Patisseries orientales", quantity: "30 pieces", city: "Tunis", publishedAt: toIsoDaysAgo(11, 16, 5), status: "disponible", receiverId: null, warningSent: false },
  { id: "don-013", donorId: "d-003", description: "Briques maison", quantity: "15 pieces", city: "Nabeul", publishedAt: toIsoDaysAgo(12, 10, 45), status: "disponible", receiverId: null, warningSent: false },
  { id: "don-014", donorId: "d-005", description: "Poulet roti", quantity: "4 portions", city: "Bizerte", publishedAt: toIsoDaysAgo(13, 13, 10), status: "reclame", receiverId: "r-005", warningSent: false },
  { id: "don-015", donorId: "d-015", description: "Haricots cuits", quantity: "6 portions", city: "Tunis", publishedAt: toIsoDaysAgo(14, 9, 2), status: "disponible", receiverId: null, warningSent: false },
  { id: "don-016", donorId: "d-010", description: "Soupes legumes", quantity: "10 portions", city: "Tunis", publishedAt: toIsoDaysAgo(16, 18, 25), status: "reclame", receiverId: "r-009", warningSent: false },
  { id: "don-017", donorId: "d-013", description: "Cakes sale", quantity: "3 plateaux", city: "Nabeul", publishedAt: toIsoDaysAgo(18, 11, 27), status: "expire", receiverId: null, warningSent: false },
  { id: "don-018", donorId: "d-002", description: "Boites de dattes", quantity: "10 boites", city: "Sfax", publishedAt: toIsoDaysAgo(22, 8, 20), status: "reclame", receiverId: "r-007", warningSent: false },
  { id: "don-019", donorId: "d-014", description: "Pizza maison", quantity: "12 parts", city: "Sousse", publishedAt: toIsoDaysAgo(25, 19, 40), status: "reclame", receiverId: "r-008", warningSent: false },
  { id: "don-020", donorId: "d-011", description: "Semoule et legumes", quantity: "9 portions", city: "Bizerte", publishedAt: toIsoDaysAgo(29, 14, 10), status: "disponible", receiverId: null, warningSent: false },
].map((item) => ({
  ...item,
  donorName: DONOR_BY_ID[item.donorId]?.name || "Donneur inconnu",
}));

const REPORTS = [
  {
    id: "rp-001",
    type: "Retard de remise",
    reportedBy: "Nour Ben Amor",
    donorId: "d-007",
    donorName: DONOR_BY_ID["d-007"].name,
    donationId: "don-011",
    status: "ouvert",
    detail: "Le donneur n'etait pas present au point de rendez-vous apres 40 minutes d'attente.",
    createdAt: toIsoDaysAgo(1, 17, 5),
  },
  {
    id: "rp-002",
    type: "Description inexacte",
    reportedBy: "Sami Kooli",
    donorId: "d-007",
    donorName: DONOR_BY_ID["d-007"].name,
    donationId: "don-006",
    status: "ouvert",
    detail: "La quantite reelle etait inferieure a celle indiquee sur la plateforme.",
    createdAt: toIsoDaysAgo(2, 15, 25),
  },
  {
    id: "rp-003",
    type: "Comportement inapproprie",
    reportedBy: "Equipe moderation",
    donorId: "d-007",
    donorName: DONOR_BY_ID["d-007"].name,
    donationId: "don-004",
    status: "ouvert",
    detail: "Echanges irrespectueux constates dans la messagerie de suivi de donation.",
    createdAt: toIsoDaysAgo(3, 12, 35),
  },
  {
    id: "rp-004",
    type: "Nourriture avariee",
    reportedBy: "Amel Jaziri",
    donorId: "d-004",
    donorName: DONOR_BY_ID["d-004"].name,
    donationId: "don-010",
    status: "resolu",
    detail: "Incident traite, compte deja suspendu et donneur notifie.",
    createdAt: toIsoDaysAgo(7, 11, 11),
  },
  {
    id: "rp-005",
    type: "Annonce dupliquee",
    reportedBy: "Meriem Khlifi",
    donorId: "d-006",
    donorName: DONOR_BY_ID["d-006"].name,
    donationId: "don-013",
    status: "ouvert",
    detail: "La meme donation a ete publiee a plusieurs reprises dans la meme journee.",
    createdAt: toIsoDaysAgo(0, 18, 2),
  },
];

const ADMIN_ACCOUNTS = [
  { id: "adm-001", name: "Sonia Admin", email: "admin@repas.tn", role: "Super Admin" },
  { id: "adm-002", name: "Kenza Moderation", email: "kenza.admin@repas.tn", role: "Moderateur" },
  { id: "adm-003", name: "Youssef Support", email: "youssef.support@repas.tn", role: "Moderateur" },
];

const QUIZ_QUESTIONS = [
  {
    id: "q-001",
    question: "Combien de temps un plat cuit peut-il rester a temperature ambiante ?",
    answers: ["30 minutes", "2 heures", "6 heures", "Toute la nuit"],
    correctAnswerIndex: 1,
  },
  {
    id: "q-002",
    question: "La meilleure methode pour refroidir rapidement un plat chaud est :",
    answers: ["Le couvrir et attendre", "Le mettre au soleil", "Le diviser en portions puis refrigerer", "Le melanger avec de l'eau"],
    correctAnswerIndex: 2,
  },
  {
    id: "q-003",
    question: "Quelle temperature est recommandee pour un refrigerateur ?",
    answers: ["0 a 4 degres", "8 a 12 degres", "15 degres", "Pas de regle"],
    correctAnswerIndex: 0,
  },
  {
    id: "q-004",
    question: "Avant de preparer un repas, il faut :",
    answers: ["Se laver les mains", "Tester le gout directement", "Laisser les aliments a l'air libre", "Utiliser le meme couteau pour tout"],
    correctAnswerIndex: 0,
  },
  {
    id: "q-005",
    question: "Pour eviter la contamination croisee, il faut :",
    answers: ["Utiliser des planches separees", "Tout melanger dans un seul bol", "Ne jamais refrigerer", "Cuire uniquement au micro-ondes"],
    correctAnswerIndex: 0,
  },
];

const EMAIL_TEMPLATES = {
  otpEmail: "Bonjour {{name}}, voici votre code OTP: {{otp}}. Ce code expire dans 10 minutes.",
  welcomeEmail: "Bienvenue sur Repas, {{name}}. Merci pour votre engagement solidaire.",
  suspensionNotice: "Votre compte a ete suspendu temporairement suite a des signalements. Contactez le support: support@repas.tn",
};

const ACTIVITY_FEED = [
  { id: "ev-001", createdAt: toIsoDaysAgo(0, 18, 30), message: "Nouveau donneur inscrit: Houda Mzoughi" },
  { id: "ev-002", createdAt: toIsoDaysAgo(0, 17, 12), message: "Donation reclamee par Nour Ben Amor" },
  { id: "ev-003", createdAt: toIsoDaysAgo(0, 16, 5), message: "Signalement recu contre Yassine Cherif" },
  { id: "ev-004", createdAt: toIsoDaysAgo(1, 14, 20), message: "Donation expiree automatiquement: Soupe chorba" },
  { id: "ev-005", createdAt: toIsoDaysAgo(1, 12, 42), message: "Compte donneur active: Hadi Khemiri" },
  { id: "ev-006", createdAt: toIsoDaysAgo(2, 19, 5), message: "Signalement resolu pour Khaled Gharbi" },
  { id: "ev-007", createdAt: toIsoDaysAgo(3, 13, 18), message: "Donation publiee: Couscous au poulet" },
  { id: "ev-008", createdAt: toIsoDaysAgo(4, 11, 40), message: "Nouveau receveur inscrit: Rami Smida" },
  { id: "ev-009", createdAt: toIsoDaysAgo(5, 9, 50), message: "Avertissement envoye a un donneur suite a signalement" },
  { id: "ev-010", createdAt: toIsoDaysAgo(6, 15, 22), message: "Donation reclamee par Amel Jaziri" },
  { id: "ev-011", createdAt: toIsoDaysAgo(7, 10, 8), message: "Compte admin ajoute: Kenza Moderation" },
  { id: "ev-012", createdAt: toIsoDaysAgo(8, 9, 30), message: "Mise a jour des questions du quiz securite alimentaire" },
];

const DEFAULT_RULES = {
  autoSuspensionOpenReports: 3,
};

export { CITY_OPTIONS };

export function buildInitialAdminState() {
  return {
    donors: DONORS.map((item) => ({ ...item, wrongAnswers: [...item.wrongAnswers] })),
    receivers: RECEIVERS.map((item) => ({ ...item })),
    donations: DONATIONS.map((item) => ({ ...item })),
    reports: REPORTS.map((item) => ({ ...item })),
    adminAccounts: ADMIN_ACCOUNTS.map((item) => ({ ...item })),
    quizQuestions: QUIZ_QUESTIONS.map((item) => ({ ...item, answers: [...item.answers] })),
    rules: { ...DEFAULT_RULES },
    emailTemplates: { ...EMAIL_TEMPLATES },
    activityFeed: ACTIVITY_FEED.map((item) => ({ ...item })),
  };
}
